version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket $S3_BUCKET --output-template-file packaged.yaml

artifacts:
  type: zip
  files:
    - template.yaml
    - packaged.yaml
